--- 
body: 
  - 
    attributes: 
      value: "Thanks for taking the time to helping out make xx better!\n"
    type: markdown
  - 
    attributes: 
      description: "A clear and concise description of what the bug is."
      label: "Describe the bug"
      placeholder: "Tell us what you see!"
    id: describe-bug
    type: textarea
    validations: 
      required: true
  - 
    attributes: 
      description: "Steps to reproduce the behavior (If applicable, add screenshots to help explain your problem)."
      label: "To Reproduce"
      value: |
          1. Go to '...'
          2. Click on '....'
          3. See error
    id: to-reproduce
    type: textarea
    validations: 
      required: true
  - 
    attributes: 
      description: "Copy the links of the concerned pages."
      label: URLs
      value: |
          - https://xxx
          - https://xx
          - ...
    id: urls
    type: textarea
    validations: 
      required: true
  - 
    attributes: 
      description: "A clear and concise description of what you expected to happen."
      label: "Expected behavior"
    id: expected-behavior
    type: textarea
    validations: 
      required: false
  - 
    attributes: 
      description: "Add any other context about the problem here."
      label: "Additional context"
    id: additional-context
    type: textarea
    validations: 
      required: false
description: "File a bug report"
labels: 
  - bug
  - triage
name: "Bug Report"
title: "[Bug]: <your-title-here>"
